language: java
jdk:
- openjdk7
- oraclejdk8
sudo: false
before_install:
- cp ./settings.xml ~/.m2/
script:
- mvn -B clean verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "openjdk7" ]] &&
  { mvn -B clean deploy -DskipTests; };'
after_script:
- mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#esbmessageadmin
    on_success: always
env:
  global:
  - secure: OUSl5MhJFaU16ByetCkJY2SQXYfvYxhbijQ/4LXbWbsuoO4R0bIWW7WCHrDtlKEj2vCu0eehHZU7cJZXT8JS1rN144RlIkf2ezdk5MmO2JIfbzMVrZUpfTn9X9H8Mf/F1XBBteowE5qUl7QFxCGJgeYmy60HYGCCI9gu3DdtUvLQdgszYlWTolGWIEb/b7H0dKo/YKnWixgF0BfK1pFomr3iqlMd8bUKaZhwzwvPtUrV5ZXNMVaE3Eisc/JIwH+T9xj+w5aWSKE9ptR9u/nSdTRnw40ItrHIiV8ZljfYHRVVlPa4fY/krHKM3e6PROoM8eSmrFnTEddEY/Xyk3XTAVCyYa7cDQaGysIASIqSv3IG/+2S/majqbPFUr00sUCZZgNyuBCITFzr2pE5CbaWHYFHxNlkuZmZm3xCiwTRPGhJsiwWJ7r481M4pszReF+xwBsdmkZmi+QS3vpBoBenza2UdEJbMqHsHujimpcTY4yVAITUYGXoP6q8poZ1p1fze29CeEhSsc40Zg772cD2oJGuMcm9nXwPKd8o382eCsOedb8/GJ6czADBqCojR9oIiCxPEMYFT3eGWSNbnSPaO7Fb8i94gE28c3eo2mkAOxqbiYjMOlVTFtu2ebmpmN5DUQ1J9uwAbUDcB/8F37/EO2pi5mUnW1oA9Uu4q3B2ses=
  - secure: wY5xH3ZGO+auY6r60X9jrfpgHosJ1SPH++KVxgoUM/sMNGWCMKvQcrXR7jwzIkw+E112gQ/A7SXLjee8NCegbpdfFrN5qLgR5wdT7ePi36/YSA2371iTglwr08dITqA1TfSp4GgYpBeVIV+TzvM1T29k44MkFKd+KImxpi5aBtJeXHf0bXDAedF6yob8nXVlCyBGnHeCsHNqpkDKBJdFiHI02b8xYaPg8WRrkVu4osDJws9zsFoMfMmG9tzKI56K5xrQLgWlF4zOuRWqQjnTHkrgwt0e3jR7Pe2zwkNgESii+y8AwAG0PokRivCRdkRDsn6fkTZs442ame3Ng1qM56ZBNVLNzaUR225+n6k8phcjnhyhE656J1TAdmkarpoN6GliFMbST/qtf2sLF1EC5dRfMNFt0pzvVac/STqCo79WdSQCxAmFEw7HohLmLXdwv3HMp+rs0VpoHNBjBZqKCXiqi7p+RLhF0AMHdvCUy0GPeEEEKlLh7REQpr6SR2q0Fji1AWlWsEmaPtfz9p2CWvBbeRja/+kPyJwSV9c1b8wWtXmxL66fmjJh+mPEHcD6W+pq1H2VXjrWVerYS4GT0cqmqEZSjFg9jS6d7RYXs58Id87O3DmO1U5PbapU20YI2Tb3lP8IQgdhKc+odfCHHcqb2wuqcWJPqdx8kSOAEm4=
